# Generated by Django 2.2.6 on 2019-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=40, verbose_name='apellidos')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cedula', models.CharField(blank=True, max_length=40, verbose_name='cedula')),
                ('phone_number', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('phone_number2', models.CharField(blank=True, max_length=40, verbose_name='celular')),
            ],
        ),
    ]
