# Generated by Django 2.2.6 on 2020-05-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slides', verbose_name='imagen')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
